
<!-- <div id="demo">
<div id="owl-demo" class="owl-carousel owl-theme">
    <div class="item"><h1>1</h1></div>
    <div class="item"><h1>2</h1></div>
    <div class="item"><h1>3</h1></div>
    <div class="item"><h1>4</h1></div>
    <div class="item"><h1>5</h1></div>
    <div class="item"><h1>6</h1></div>
    <div class="item"><h1>7</h1></div>
    <div class="item"><h1>8</h1></div>
</div>
</div> -->


<!-- <script>

    require([
        'jquery',
        'owlcarouselslider'
        ], function () {
            'use strict';
            jQuery.noConflict();
                jQuery(".owl-carousel").owlCarousel({
                autoPlay: 3000, //3000 Set AutoPlay to 3 seconds
                margin:5,
                items : 5,
                itemsDesktop : [1199,5],
                itemsDesktopSmall : [979,5],
                itemsTablet : [768,5],
                navigation : true,
                pagination : false
          });
    });
</script> -->
<!-- <script type="text/javascript">
require([
    'jquery',
    'owlslider'  // the alias for "mage/accordion"
], function ($) {
    $(function () {
        var products_list = $('.owl-carousel');
        products_list.owlCarousel({  
        loop:true,
        margin:30,
        nav:true,
        autoplay:false,
        autoplayTimeout:3000,

        dots:false,
        responsive:{
            0:{
                items:4
            },  
            
            1200:{
                items:4   
            }
        }
})
    });
});
</script> -->


<div id="demo">
 
    <div id="owl-demo" class="owl-carousel">
 
        <div class="item"><h1>1</h1></div>
        <div class="item"><h1>2</h1></div>
        <div class="item"><h1>3</h1></div>
        <div class="item"><h1>4</h1></div>
        <div class="item"><h1>5</h1></div>
        <div class="item"><h1>6</h1></div>
        <div class="item"><h1>7</h1></div>
        <div class="item"><h1>8</h1></div>
        <div class="item"><h1>9</h1></div>
        <div class="item"><h1>10</h1></div>
        <div class="item"><h1>11</h1></div>
        <div class="item"><h1>12</h1></div>
 
    </div>
 
</div>
 
<script>
    require([
        'cookiecode/jquery',
        'owlcarousel',
    ], function ($) {
        jQuery(document).ready(function () {
            jQuery("#owl-demo").owlCarousel({
                navigation: true
            });
        });
    });
</script>