<div class="title">
        <h2>Newsletter Sign Up</h2>
            <span>Subscribe to our newsletter and get 10% off your first purchase </span>
        </div>
<section class="newsletter-section">
    <div class="block newsletter">
        <div class="content">
            <form class="form subscribe"
                novalidate
                action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
                method="post"
                data-mage-init='{"validation": {"errorClass": "mage-error"}}'
                id="newsletter-validate-detail">
                <div class="field newsletter">
                    <label class="label" for="newsletter"><span>Subscribe to our newsletter and get 10% off your first purchase </span></label>
                    <div class="control">
                        <input name="email" type="email" id="newsletter"
                                    placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>"
                                    data-validate="{required:true, 'validate-email':true}"/>
                    </div>
                </div>
                <div class="actions">
                    <button class="action subscribe" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
                        <span><?php /* @escapeNotVerified */ echo __('Subscribe') ?></span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</section>
